### ISSUE TITLE
Pass server address via command line parameter

### ISSUE THREAD

**Issue by maweki** [xkonni/snapcastr#1]
This would be very useful instead of having to change file contents. I do an orchestrated deployment of my snapcast-stuff via ansible and changing file contents is a hassle.

One could use `argparser` to just parse the server address.

I'll try to create PR in the next few days, if that's okay?!

**Comment by xkonni** [comment]
update:
uhm. after looking into the code again, that's already there. 
``` snapcastrd --host foo --port 12345 ```

**Comment by maweki** [comment]
Those parameters are the host and port to bind to, not the host and port of the snapserver.
