### ISSUE TITLE
Clients hostnames are not resolved, shown as mac

### ISSUE THREAD

**Issue by praul** [xkonni/snapcastr#14]
Hi. First of all thx for this control, since it's the only one that is really easy and fast to install without a lot of dependencies.

I run snapcastr on my snapcast server with 
> snapcastrd --bind=0.0.0.0 --port=5011 --host=127.0.0.1

It's working fine so far, but clients hostnames are not resolved and shown as mac adresses.
The snapcast control apk does this without problems, so I guess it's not a server problem.

Any idea what could be wrong? Thanks

**Comment by apirogov** [comment]
I have the same problem, would be nice if this was fixed!

**Comment by petershaw23** [comment]
same here
![image](https://user-images.githubusercontent.com/44604841/65787432-39d35180-e159-11e9-9efc-99deb7c6fd12.png)
