### ISSUE TITLE
error in running server

### ISSUE THREAD

**Issue by karba78** [xkonni/snapcastr#5]
hello; any idea on root cause for error below; thks

`pi@pi2-snapcaslt-client-01:~/snapcastr $ sudo snapcastrd --host=0.0.0.0 --port=5011
Traceback (most recent call last):
  File "/usr/local/bin/snapcastrd", line 4, in <module>
    import snapcastr
  File "/usr/local/lib/python2.7/dist-packages/snapcastr/__init__.py", line 1, in <module>
    from .snapcastr import app
  File "/usr/local/lib/python2.7/dist-packages/snapcastr/snapcastr.py", line 40
    return (yield from snapcast.control.create_server(loop, server_addr, reconnect=True))
                     ^
SyntaxError: invalid syntax
pi@pi2-snapcaslt-client-01:~/snapcastr $ 
`

**Comment by xkonni** [comment]
I guess you modified the source to make it use python2, but it really needs python3. 
Oh and it does not need root privileges, you can omit the _sudo_.

**Comment by karba78** [comment]
thks
nope did not  modify the source  and checked i indeed have python 3 installed

**Comment by xkonni** [comment]
mhhm. it's odd though, that
```
#!/usr/bin/env python3
```
ends up with python2 - as you can see from your output. Make sure it's using python3 instead ;)

**Comment by heiderich** [comment]
I experience the same problem.

How do I make sure that snapcastr is installed as a python3 program?

**Comment by maweki** [comment]
You don't actually need to install `snapcastr`. If you clone it and install the dependencies you can launch it from the same working directory using `PYTHONPATH=. python3 bin/snapcastrd`

**Comment by mariolukas** [comment]
I had the same issue. I tried to install with pip on Raspbian. `python --version` showed that it was using python2.7  by default.

Python 3 was also installed on my system. A simple `pip3 install .` worked for me. This installs the package in Python 3 context.

**Comment by xkonni** [comment]
should be easier now with the latest changes and pypi.
